global.OverallControllerLeftStickH = 0;	// Between -1 and 0 is left, between 0 and 1 is right.
global.OverallControllerLeftStickV = 0; // Between -1 and 0 is up, between 0 and 1 is down.
global.OverallControllerRightStickH = 0; // Between -1 and 0 is left, between 0 and 1 is right.
global.OverallControllerRightStickV = 0; // Between -1 and 0 is up, between 0 and 1 is down.
global.OverallControllerAButton = false; // gp_face1 (A or Cross) for Gamepads, Z Key for Keyboard.
global.OverallControllerBButton = false; // gp_face2 (B or Circle) for Gamepads, X Key for Keyboard.
global.OverallControllerXButton = false; // gp_face3 (X or Square) for Gamepads, C Key for Keyboard.
global.OverallControllerYButton = false; // gp_face4 (Y or Triangle) for Gamepads, V Key for Keyboard.
global.OverallControllerLTButton = false; // gp_shoulderlb (LT) for Gamepads, A Key for Keyboard.
global.OverallControllerRTButton = false; // gp_shoulderrb (RT) for Gamepads, S Key for Keyboard.
global.OverallControllerLBButton = false; // gp_shoulderl (LB) for Gamepads, Ctrl Key for Keyboard.
global.OverallControllerRBButton = false; // gp_shoulderr (RB) for Gamepads, Shift Key for Keyboard.
global.OverallControllerStartButton = false; // gp_start (Start) for Gamepads, Escape or Enter Key for Keyboard.
global.OverallControllerSelectButton = false; // gp_select (Select) for Gamepads, Backspace Key for Keyboard.